import type { ParsedMail } from "mailparser";

// D-12/D-13: pure predicate over parsed headers detecting auto-generated mail
// (RFC 3834 auto-reply, Precedence bulk, bounce/DSN, mailing-list traffic).
// Auto-generated mail never creates a new ticket and never triggers
// auto-reopen (D-13) — the ingest orchestrator (plan 04) is the caller that
// enforces that behavior; this function only detects.
export function isAutoGenerated(parsed: ParsedMail): boolean {
  const autoSubmitted = String(parsed.headers.get("auto-submitted") ?? "no").toLowerCase();
  if (autoSubmitted !== "no") return true; // RFC 3834 §5.2: "auto-generated" | "auto-replied"

  if (parsed.headers.has("x-auto-response-suppress")) return true;

  const precedence = String(parsed.headers.get("precedence") ?? "").toLowerCase();
  if (["bulk", "junk", "auto_reply", "list"].includes(precedence)) return true;

  const returnPath = parsed.headers.get("return-path");
  if (returnPath && String(returnPath).trim() === "<>") return true; // null return-path = bounce

  const contentType = parsed.headers.get("content-type") as { value?: string } | undefined;
  if (contentType?.value === "multipart/report") return true; // DSN/bounce (RFC 3464)

  // List-Id: mailparser aggregates List-* headers into a "list" object; the
  // exact sub-shape for List-Id specifically isn't pinned down by docs
  // (03-RESEARCH.md Open Question 1) — defensive dual check also scans the
  // raw headerLines for a "list-id" key so detection doesn't silently depend
  // on one parsed shape.
  const list = parsed.headers.get("list") as { id?: unknown } | undefined;
  if (list?.id) return true;
  if (parsed.headerLines?.some((h) => h.key === "list-id")) return true;

  return false;
}
