// Inbound ingest orchestrator (D-08..D-20): parse -> dedupe -> auto-detect ->
// thread-match -> sanitize/attach -> create-or-append + auto-reopen.
//
// Worker-bundleable (esbuild) — every project import below is RELATIVE, never the
// Next.js path alias (this module is transitively required by src/lib/worker/index.ts
// via poll-inbox.ts).
import { createHash, randomBytes } from "node:crypto";
import { fileTypeFromBuffer } from "file-type";
import { simpleParser } from "mailparser";
import { ALLOWED_MIME, MAX_BYTES } from "../../attachments/constants";
import { buildStorageKey, localFileStorage } from "../../attachments/local-file-storage";
import { renderMarkdown, sanitizeEmailHtml } from "../../markdown/render";
import { scopedDb } from "../../scoped-db";
import { createTicket } from "../../tickets/create-ticket";
import { isAutoGenerated } from "./auto-generated";
import { extractEmailBody } from "./parse-body";
import {
  collectCandidateMessageIds,
  extractSubjectTicketNumber,
  findTicketByNumber,
  findTicketIdByEmailMessageIds,
} from "./thread-match";

/**
 * Deterministically derives the dedupe/poison key for a physical email. MUST NOT use
 * randomBytes/randomUUID here — a fresh random id per call would make a retried ingest
 * of the SAME email look new, defeating the Message-ID dedupe (D-05) and the poison
 * guard (D-06). Falls back to a content hash only when the sender omitted Message-ID,
 * so even that case is stable across re-polls.
 */
export function deriveEmailMessageId(
  rawSource: Buffer | string,
  parsedMessageId: string | null | undefined,
): string {
  return parsedMessageId ?? `<${createHash("sha256").update(rawSource).digest("hex")}@aida.local>`;
}

// Untrusted, attacker-controllable strings (attachment filenames) are escaped before
// being appended to an ALREADY-sanitized bodyHtml string (sanitizeEmailHtml already ran
// by the time this note is appended, so this is the only guard against HTML injection
// here — ticket text is untrusted input, CLAUDE.md).
function escapeHtml(s: string): string {
  return s.replace(
    /[&<>"']/g,
    (c) =>
      (
        {
          "&": "&amp;",
          "<": "&lt;",
          ">": "&gt;",
          '"': "&quot;",
          "'": "&#39;",
        } as Record<string, string>
      )[c] as string,
  );
}

type SavedAttachment = {
  id: string;
  cid: string | null;
  storageKey: string;
  originalFilename: string;
  mimeType: string;
  sizeBytes: number;
};

/**
 * Ingests one physical inbound email: dedupe -> self-loop guard -> thread-match ->
 * sanitize body + save attachments -> create-or-append (with auto-reopen mirroring the
 * Phase 2 follow-up route). `emailMessageId` is computed ONCE by the caller (poll-inbox,
 * via deriveEmailMessageId) and passed in here — never re-derived/re-synthesized.
 */
export async function ingestMessage(
  orgId: string,
  rawSource: Buffer | string,
  selfAddress: string,
  emailMessageId: string,
): Promise<"created" | "appended" | "duplicate" | "skipped" | "dropped-auto"> {
  const parsed = await simpleParser(rawSource);
  const db = scopedDb(orgId);

  // Self-loop guard (D-14): never let the workspace's own address create a loop.
  const from = parsed.from?.value?.[0]?.address?.toLowerCase();
  if (from && from === selfAddress.toLowerCase()) return "skipped";

  // Dedupe (D-05): the same physical email, re-polled or re-ingested, never double-creates.
  const existing = await db.message.findFirst({ where: { emailMessageId } });
  if (existing) return "duplicate";

  const isAuto = isAutoGenerated(parsed);

  // Already capped to the last 10 (D-23's reference-chain cap applies symmetrically to
  // inbound storage) — reused as-is in every Message-create branch below.
  const emailReferences = (
    Array.isArray(parsed.references)
      ? parsed.references
      : parsed.references
        ? [parsed.references]
        : []
  ).slice(-10);

  // Thread-match (D-08 header match, then D-09 subject-token fallback).
  let ticketId = await findTicketIdByEmailMessageIds(db, collectCandidateMessageIds(parsed));
  if (!ticketId) {
    const n = extractSubjectTicketNumber(parsed.subject);
    if (n) {
      const matched = await findTicketByNumber(db, n);
      ticketId = matched?.id ?? null;
    }
  }

  let matchedTicket: { id: string; status: string; contactId: string } | null = null;
  if (ticketId) {
    matchedTicket = await db.ticket.findFirst({ where: { id: ticketId } });
  }

  // Body + attachments — single canonical pass, ids pre-generated so there is exactly
  // ONE write per row below (no post-insert db.message.update).
  const { rawHtml, text: extractedText } = extractEmailBody(parsed);
  let text = extractedText;

  const saved: SavedAttachment[] = [];
  const droppedNames: string[] = [];

  for (const att of parsed.attachments ?? []) {
    const filename = att.filename ?? "attachment";
    if (att.size > MAX_BYTES) {
      droppedNames.push(filename);
      continue;
    }
    const sniffed = await fileTypeFromBuffer(att.content);
    if (!sniffed || !ALLOWED_MIME.has(sniffed.mime)) {
      droppedNames.push(filename);
      continue;
    }
    // Pre-generate the id up front (Attachment.id is String @id @default(cuid()) —
    // an explicit id is allowed, mirrors local-file-storage's own id pattern) so the
    // cid -> id map below is known BEFORE any DB write.
    const id = randomBytes(16).toString("hex");
    const storageKey = buildStorageKey(filename);
    await localFileStorage.save({ orgId, key: storageKey, data: att.content });
    saved.push({
      id,
      cid: att.cid ?? null,
      storageKey,
      originalFilename: filename,
      mimeType: sniffed.mime,
      sizeBytes: att.size,
    });
  }

  if (droppedNames.length > 0) {
    text += `\n\n[${droppedNames.length} attachment(s) not stored (too large or unsupported): ${droppedNames.join(", ")}]`;
  }

  // cid -> id map built directly from `saved` (inline attachments = those with a cid).
  const cidMap = new Map<string, string>();
  for (const file of saved) {
    if (file.cid) cidMap.set(file.cid, file.id);
  }

  // Compute bodyHtml ONCE, up front, from that map — the message + Attachment rows are
  // then written together in the single transaction below with this final bodyHtml.
  let bodyHtml: string;
  if (rawHtml) {
    let rewritten = rawHtml;
    for (const [cid, id] of cidMap) {
      rewritten = rewritten.split(`cid:${cid}`).join(`/api/attachments/${id}`);
    }
    bodyHtml = sanitizeEmailHtml(rewritten);
    if (droppedNames.length > 0) {
      bodyHtml += `<p>${escapeHtml(
        `${droppedNames.length} attachment(s) not stored (too large or unsupported): ${droppedNames.join(", ")}`,
      )}</p>`;
    }
  } else {
    bodyHtml = renderMarkdown(text);
  }

  const contact = {
    email: from ?? "unknown@unknown.invalid",
    name: parsed.from?.value?.[0]?.name ?? null,
  };

  if (matchedTicket) {
    // Auto mail threads normally but never reopens (D-13).
    const shouldReopen =
      !isAuto && (matchedTicket.status === "RESOLVED" || matchedTicket.status === "CLOSED");
    const ticketIdToUpdate = matchedTicket.id;
    const authorContactId = matchedTicket.contactId;

    await db.$transaction(async (tx) => {
      const created = await tx.message.create({
        data: {
          organizationId: orgId,
          ticketId: ticketIdToUpdate,
          direction: "INBOUND",
          visibility: "PUBLIC",
          authorContactId,
          bodyMarkdown: text,
          bodyHtml,
          emailMessageId,
          emailInReplyTo: parsed.inReplyTo ?? null,
          emailReferences,
          triggeredReopen: shouldReopen,
        },
      });

      for (const file of saved) {
        await tx.attachment.create({
          data: {
            id: file.id,
            organizationId: orgId,
            messageId: created.id,
            storageKey: file.storageKey,
            originalFilename: file.originalFilename,
            mimeType: file.mimeType,
            sizeBytes: file.sizeBytes,
          },
        });
      }

      if (shouldReopen) {
        await tx.ticket.update({
          where: { id: ticketIdToUpdate },
          data: { status: "OPEN", resolvedAt: null },
        });
      }
    });

    return "appended";
  }

  // No thread match at all.
  if (isAuto) return "dropped-auto"; // D-13: auto mail never creates a new ticket.

  const result = await createTicket(orgId, {
    subject: parsed.subject ?? "(no subject)",
    priority: "NORMAL",
    body: text,
    bodyHtml: rawHtml ? bodyHtml : undefined,
    contact,
    direction: "INBOUND",
    emailMessageId,
    emailInReplyTo: parsed.inReplyTo ?? null,
    emailReferences,
  });

  for (const file of saved) {
    await db.attachment.create({
      data: {
        id: file.id,
        organizationId: orgId,
        messageId: result.messageId,
        storageKey: file.storageKey,
        originalFilename: file.originalFilename,
        mimeType: file.mimeType,
        sizeBytes: file.sizeBytes,
      },
    });
  }

  return "created";
}
