import { describe, expect, it } from "vitest";
import type { ParsedMail } from "mailparser";
import { isAutoGenerated } from "@/lib/channels/email/auto-generated";
import { collectCandidateMessageIds, extractSubjectTicketNumber } from "@/lib/channels/email/thread-match";

function makeParsed(headers: Record<string, unknown>, headerLines: { key: string; line: string }[] = []) {
  return {
    headers: new Map(Object.entries(headers)),
    headerLines,
  } as unknown as ParsedMail;
}

describe("extractSubjectTicketNumber", () => {
  it("extracts the ticket number token from a subject", () => {
    expect(extractSubjectTicketNumber("Re: Login broken [#42]")).toBe(42);
  });

  it("returns null when no token is present", () => {
    expect(extractSubjectTicketNumber("no token here")).toBeNull();
  });
});

describe("collectCandidateMessageIds", () => {
  it("dedupes and filters falsy values, preserving order", () => {
    const result = collectCandidateMessageIds({
      inReplyTo: "<a@h>",
      references: ["<a@h>", "<b@h>"],
    });
    expect(result).toEqual(["<a@h>", "<b@h>"]);
  });
});

describe("isAutoGenerated", () => {
  it("detects Auto-Submitted: auto-replied", () => {
    expect(isAutoGenerated(makeParsed({ "auto-submitted": "auto-replied" }))).toBe(true);
  });

  it("detects Precedence: bulk", () => {
    expect(isAutoGenerated(makeParsed({ precedence: "bulk" }))).toBe(true);
  });

  it("detects a null Return-Path (bounce)", () => {
    expect(isAutoGenerated(makeParsed({ "return-path": "<>" }))).toBe(true);
  });

  it("detects multipart/report content-type (DSN/bounce)", () => {
    expect(isAutoGenerated(makeParsed({ "content-type": { value: "multipart/report" } }))).toBe(true);
  });

  it("detects a List-Id header via headerLines fallback", () => {
    expect(
      isAutoGenerated(makeParsed({}, [{ key: "list-id", line: "List-Id: <list.example.com>" }])),
    ).toBe(true);
  });

  it("returns false for an ordinary human reply", () => {
    expect(isAutoGenerated(makeParsed({ "auto-submitted": "no" }))).toBe(false);
  });
});
